version: 2 

sources:
    - name: stage
      database: dev
      schema: stage
      tables:
        - name: listen_events
          meta: 
            dagster:
              asset_key: ['stage_listen_events']
        - name: page_view_events
          meta: 
            dagster:
              asset_key: ['stage_page_view_events']
        - name: auth_events
          meta: 
            dagster:
              asset_key: ['stage_auth_events']
        - name: status_change_events
          meta: 
            dagster:
              asset_key: ['stage_status_change_events']