from pyflink.table import DataTypes
from pyflink.table.schema import Schema

schemas = {
    'listen_events': Schema.new_builder()
        .column("artist", DataTypes.STRING())
        .column("song", DataTypes.STRING())
        .column("duration", DataTypes.DOUBLE())
        .column("ts", DataTypes.BIGINT())
        .column("sessionid", DataTypes.INT())
        .column("auth", DataTypes.STRING())
        .column("level", DataTypes.STRING())
        .column("itemInSession", DataTypes.INT())
        .column("city", DataTypes.STRING())
        .column("zip", DataTypes.INT())
        .column("state", DataTypes.STRING())
        .column("userAgent", DataTypes.STRING())
        .column("lon", DataTypes.DOUBLE())
        .column("lat", DataTypes.DOUBLE())
        .column("userId", DataTypes.BIGINT())
        .column("lastName", DataTypes.STRING())
        .column("firstName", DataTypes.STRING())
        .column("gender", DataTypes.STRING())
        .column("registration", DataTypes.BIGINT())
        .build(),

    'page_view_events': Schema.new_builder()
        .column("ts", DataTypes.BIGINT())
        .column("sessionId", DataTypes.INT())
        .column("page", DataTypes.STRING())
        .column("auth", DataTypes.STRING())
        .column("method", DataTypes.STRING())
        .column("status", DataTypes.INT())
        .column("level", DataTypes.STRING())
        .column("itemInSession", DataTypes.INT())
        .column("city", DataTypes.STRING())
        .column("zip", DataTypes.INT())
        .column("state", DataTypes.STRING())
        .column("userAgent", DataTypes.STRING())
        .column("lon", DataTypes.DOUBLE())
        .column("lat", DataTypes.DOUBLE())
        .column("userId", DataTypes.INT())
        .column("lastName", DataTypes.STRING())
        .column("firstName", DataTypes.STRING())
        .column("gender", DataTypes.STRING())
        .column("registration", DataTypes.BIGINT())
        .column("artist", DataTypes.STRING())
        .column("song", DataTypes.STRING())
        .column("duration", DataTypes.DOUBLE())
        .build(),

    'auth_events': Schema.new_builder()
        .column("ts", DataTypes.BIGINT())
        .column("sessionId", DataTypes.INT())
        .column("level", DataTypes.STRING())
        .column("itemInSession", DataTypes.INT())
        .column("city", DataTypes.STRING())
        .column("zip", DataTypes.INT())
        .column("state", DataTypes.STRING())
        .column("userAgent", DataTypes.STRING())
        .column("lon", DataTypes.DOUBLE())
        .column("lat", DataTypes.DOUBLE())
        .column("userId", DataTypes.INT())
        .column("lastName", DataTypes.STRING())
        .column("firstName", DataTypes.STRING())
        .column("gender", DataTypes.STRING())
        .column("registration", DataTypes.BIGINT())
        .column("success", DataTypes.BOOLEAN())
        .build()
}
